# Generated by Django 4.1.3 on 2023-04-16 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='objective', max_length=100)),
                ('questionNumbers', models.IntegerField(default=50, max_length=3)),
                ('duration', models.IntegerField(default=1, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TestTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(default='Natural Resources', max_length=100)),
                ('description', models.CharField(default='This is Default description', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestGivingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testAssigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.testdata')),
            ],
        ),
        migrations.AddField(
            model_name='testdata',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.testtopic'),
        ),
    ]
