# Generated by Django 4.1.3 on 2023-04-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='testName',
            field=models.CharField(default='testDefaultName', max_length=100),
        ),
    ]
