# Generated by Django 4.1.3 on 2023-05-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0004_rename_type_testdata_testtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='attempted',
            field=models.BooleanField(default=True),
        ),
    ]
