# Generated by Django 4.1.3 on 2023-08-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0005_testdata_attempted'),
    ]

    operations = [
        migrations.CreateModel(
            name='flashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardData', models.CharField(default='natural resources', max_length=100)),
            ],
        ),
    ]
