# Generated by Django 4.1.3 on 2023-08-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0006_flashcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='cardTopic',
            field=models.CharField(default='natural resources', max_length=100),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='slNumber',
            field=models.IntegerField(default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='cardData',
            field=models.CharField(default="{'frontBg' :'#F5F7E4', 'frontContent': '1st front side', 'backBg':'blue', 'backContent':'1st back side'}", max_length=100),
        ),
    ]
