# Generated by Django 4.1.3 on 2023-09-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0009_flashcardtopic_userreaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userreaction',
            name='flascard',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='cardTopic',
            field=models.CharField(default='natural resources', max_length=700),
        ),
        migrations.DeleteModel(
            name='FlashCardTopic',
        ),
        migrations.DeleteModel(
            name='UserReaction',
        ),
    ]
