# Generated by Django 4.1.3 on 2023-09-04 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0010_remove_userreaction_flascard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='Chemicals', max_length=20)),
                ('desc', models.CharField(default='Description for Chemicals', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=1, max_length=4)),
                ('reaction', models.CharField(default=None, max_length=20)),
                ('relatedCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.flashcard')),
            ],
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='cardTopic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendApp.flashcardtopic'),
        ),
    ]
