# Generated by Django 4.1.3 on 2023-09-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0011_flashcardtopic_userreaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreaction',
            name='reaction',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
