# Generated by Django 4.1.3 on 2023-09-05 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0013_alter_flashcardtopic_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreaction',
            name='dateTime',
            field=models.DateTimeField(default=datetime.date(2023, 9, 6)),
        ),
        migrations.AlterField(
            model_name='flashcardtopic',
            name='desc',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='flashcardtopic',
            name='topic',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='userreaction',
            name='reaction',
            field=models.CharField(default='None', max_length=7),
        ),
    ]
