# Generated by Django 4.1.3 on 2023-09-12 08:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0015_alter_flashcard_carddata_alter_userreaction_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=1, max_length=4)),
                ('startTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='userreaction',
            name='dateTime',
            field=models.DateTimeField(default=datetime.date(2023, 9, 12)),
        ),
        migrations.AlterField(
            model_name='userreaction',
            name='reaction',
            field=models.CharField(default='undeclaired', max_length=7),
        ),
        migrations.AddField(
            model_name='userreaction',
            name='session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backendApp.session'),
        ),
    ]
