# Generated by Django 4.1.3 on 2023-09-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0018_alter_session_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
