# Generated by Django 4.1.3 on 2023-09-24 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0020_flashcarduserreaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardsession',
            name='reactionRecorded',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='flashcarduserreaction',
            name='dateTime',
            field=models.DateTimeField(default=datetime.date(2023, 9, 24)),
        ),
    ]
