# Generated by Django 4.1.3 on 2023-09-24 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0024_flashcardsession_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcardsession',
            name='topic',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='backendApp.flashcardtopic'),
        ),
    ]
