# Generated by Django 4.1.3 on 2023-09-24 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0025_alter_flashcardsession_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcardsession',
            name='topic',
        ),
    ]
