# Generated by Django 4.1.3 on 2023-10-19 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendApp', '0027_flashcardsession_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(default='natural resources', max_length=100)),
                ('topicDescription', models.CharField(default='this is default description', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='testdata',
            name='topicDescription',
        ),
        migrations.RemoveField(
            model_name='testdata',
            name='topicName',
        ),
        migrations.AddField(
            model_name='testdata',
            name='testStatus',
            field=models.IntegerField(default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='flashcarduserreaction',
            name='dateTime',
            field=models.DateTimeField(default=datetime.date(2023, 10, 19)),
        ),
        migrations.AddField(
            model_name='testdata',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backendApp.testtopic'),
        ),
    ]
